version: '3'
services:
  angular-app:
    build:
      context: ./FalaParaTexto.UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - my_network

  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
